version: "3"
services : 
  itam_ui:
    build : 
      context : .
      dockerfile : Dockerfile.dev
    ports:
      - "4200:4200"
    expose:
      - "4200"
    volumes:
      - /app/node_modules
      - .:/app

